ThreePillarsinfo-Scrum50
Memai2023/scrum-guide pull request #5
Opened 2024-05-06 18:45 UTC by africandeluxe

**Annan design än Figma. OK av team än så länge**

Second part: Essence - Three pillars of empiricism

- Three paragraph components 
- Textcontent imported from data.js 
- Responsive: a flexbox container with all three paragraphs, as window narrows they stack on top (e.g. using flex-wrap:wrap)

2024-05-06 19:59 UTC, Memai2023 requested changes
Hej, kan du kolla indenteringen i koden som jag markerade?

2024-05-06 19:59 UTC, Memai2023 commented on src/Components/Essence/ThreePillarsInfo/index.jsx
> +        <PillarCard title="Inspection" text={Essence.inspectionText} postScript={Essence.inspectionPS} className={styles.firstcard} />
Här behöver koden indenteras från rad 19 till 22, kan du ändra?

2024-05-07 11:24 UTC, blombergalex approved these changes
Snyggt! Det som efterfrågades innan har åtgärdats. Bara en rad av repeterad kod du kan ta bort, du behöver inte fråga om ny CR efter det. Bra jobbat!!!

2024-05-07 11:24 UTC, blombergalex commented on src/Components/Essence/ThreePillarsInfo/ThreePillarsInfo.module.css
> +  flex-basis: 30%;
rad 18 kan tas bort, du har redan definierat flex-basis i rad 12
flex: 1 1 30%  = flew-grow:1, flex-shrink:1, flex-basis: 30%

2024-05-07 11:41 UTC, africandeluxe commented on src/Components/Essence/ThreePillarsInfo/ThreePillarsInfo.module.css
> +  flex-basis: 30%;
Aaaaah förstår! Den är borttagen :)

2024-05-07 13:38 UTC, blombergalex approved these changes
Snyggt! Redo att överföras i nya projektet :)

2024-05-11 13:08 UTC, merged